runcmd:
#- sudo apt update
#- sudo apt install redis-server
- sudo echo "supervised systemd" >> /etc/redis/redis.conf
- sudo echo "bind 0.0.0.0" >> /etc/redis/redis.conf
- sudo systemctl restart redis.service
- sudo systemctl status redis
# - sudo apt install redis-tools
package_upgrade: true
packages:
- redis 
- redis-tools
